#!/bin/bash

baseFolder=$PWD

if [ ! -d "ccm26ToFoam" ]; then

  echo "Preparing folder ccm26ToFoam..."

  cp -r $FOAM_APP/utilities/mesh/conversion/Optional/ccm26ToFoam .

  sed -i -e 's=FOAM_APPBIN=FOAM_USER_APPBIN=' ccm26ToFoam/Make/files
  sed -i -e 's|^LIBCCMIO_DIR.*|LIBCCMIO_DIR = $(realpath ../libccmio-2.6.1)|' ccm26ToFoam/Make/options
  sed -i -e 's=FOAM_EXT_LIBBIN=FOAM_USER_LIBBIN=' ccm26ToFoam/Make/options
  wget -O "ccm26ToFoam/ccm26ToFoam.C" \
  "https://raw.github.com/OpenFOAM/OpenFOAM-2.2.x/f5bc1812790674c3f30dcb7d158af7a51d41fc4b/applications/utilities/mesh/conversion/Optional/ccm26ToFoam/ccm26ToFoam.C"
  
  mkdir download

fi

cat<<USAGE
* The license of the libccmio library is proprietary:

    Users wishing to make use of its functionality should contact CD-Adapco
    for possible download and terms of use.

Have you contacted CD-Adapco and received the libccmio package?

  - If you have, then press Enter to continue. It will download the package available at the VisIt project.

  - If you have not, then press the key combination Ctrl+C to abort.
USAGE
read a

(
  ./AllwmakeLibccmio DownloadFromVisIt && \
  wmake ccm26ToFoam && wmake ccm26ToFoam
) 2>&1 | tee build.log

echo ""
echo "The output above has been logged inside the file 'build.log'."
