#!/bin/bash

baseFolder=$PWD

if [ ! -d "ccm26ToFoam" ]; then

  echo "Preparing folder ccm26ToFoam..."

  cp -r $FOAM_APP/utilities/mesh/conversion/Optional/ccm26ToFoam .

  sed -i -e 's=FOAM_APPBIN=FOAM_USER_APPBIN=' ccm26ToFoam/Make/files
  sed -i -e 's|^LIBCCMIO_DIR.*|LIBCCMIO_DIR = $(realpath ../libccmio-2.6.1)|' ccm26ToFoam/Make/options
  sed -i -e 's=FOAM_EXT_LIBBIN=FOAM_USER_LIBBIN=' ccm26ToFoam/Make/options
  wget -O "ccm26ToFoam/ccm26ToFoam.C" \
  "https://raw.github.com/OpenFOAM/OpenFOAM-2.2.x/f5bc1812790674c3f30dcb7d158af7a51d41fc4b/applications/utilities/mesh/conversion/Optional/ccm26ToFoam/ccm26ToFoam.C"
  
  mkdir download

fi

cat<<USAGE
* The license of the libccmio library is proprietary:

    Users wishing to make use of its functionality should contact CD-Adapco
    for possible download and terms of use.

Have you contacted CD-Adapco and received the libccmio package? (yes/no): 
USAGE
read theAnswer

if [ "$theAnswer" = "yes" ]; then
  
  (
    ./AllwmakeLibccmio DownloadFromVisIt && \
    wmake ccm26ToFoam
  ) | tee build.log 2>&1

else
  
  cat<<FINALMESSAGE
Once you've contacted CD-Adapco and you have received the libccmio package, 
place the package in this folder:

    $PWD/download/

And run this script once again.
FINALMESSAGE

fi
